<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Just Now_StyledImage-sc-ey4zx9-0 hydiME</name>
   <tag></tag>
   <elementGuidId>45380999-37b9-4dca-a5b2-c1490b4be364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ScrollableDiv']/div/div/div/div/div/div[2]/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.StyledBox-sc-13pk1d4-0.jLuQqX > img.StyledImage-sc-ey4zx9-0.hydiME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af82e891-cd6e-4f50-a980-c7e3050eab53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://insim-storage.knolskape.com/product/insim/ei/assets/replyIcon.png</value>
      <webElementGuid>5552ffc5-6828-422a-96cd-82fa99a7a593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledImage-sc-ey4zx9-0 hydiME</value>
      <webElementGuid>8900358e-5192-4244-a81c-7adc1c11d9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ScrollableDiv&quot;)/div[@class=&quot;StyledBox-sc-13pk1d4-0 hRPfZf&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 iVnPXM&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 frhMkV&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 ihfbaW&quot;]/div[1]/div[@class=&quot;StyledBox-sc-13pk1d4-0 hvNOzz&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 RBDMu mailSummaryReply&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 befjQ replyButton&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 jLuQqX&quot;]/img[@class=&quot;StyledImage-sc-ey4zx9-0 hydiME&quot;]</value>
      <webElementGuid>eb6be7c1-521e-4808-b5c6-ec21aac7b66d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ScrollableDiv']/div/div/div/div/div/div[2]/div/div/div/img</value>
      <webElementGuid>3c4ebb14-22ec-4aeb-9048-76f24c6b8446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://insim-storage.knolskape.com/product/insim/ei/assets/replyIcon.png')]</value>
      <webElementGuid>182eebbf-14e2-4ac1-843b-e403576fa32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>6cb919e8-c6a1-481c-8757-9f232f983993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://insim-storage.knolskape.com/product/insim/ei/assets/replyIcon.png']</value>
      <webElementGuid>c2230361-5863-435c-8fde-4d178c42ae0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
