<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1 New Response</name>
   <tag></tag>
   <elementGuidId>ffa107b5-9d18-405d-acf2-8c4702483dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ScrollableDiv']/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.StyledText-sc-1sadyjn-0.iNsKZp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7fb6fe8b-2697-48fa-b339-9614bdeafb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledText-sc-1sadyjn-0 iNsKZp</value>
      <webElementGuid>3f1704c6-590f-4013-b111-5ea9d142112b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 New Response</value>
      <webElementGuid>6a733c73-5702-468d-b07b-f0379d0bf1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ScrollableDiv&quot;)/div[@class=&quot;StyledBox-sc-13pk1d4-0 fTOJCw&quot;]/span[@class=&quot;StyledText-sc-1sadyjn-0 iNsKZp&quot;]</value>
      <webElementGuid>45fda65b-2964-425b-9a9f-86208256f74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ScrollableDiv']/div[2]/span</value>
      <webElementGuid>a31d8248-17be-4bb6-a27f-43022e4d292d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just Now'])[3]/following::span[2]</value>
      <webElementGuid>f3b43752-d3b2-4e65-a407-0bb0b924eae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emery'])[2]/following::span[2]</value>
      <webElementGuid>af36f1ed-290a-4a89-bb1a-b3ab73a8d8d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 New Response']/parent::*</value>
      <webElementGuid>6e7635d2-b64c-4da2-8836-5c0f7f89be7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/span</value>
      <webElementGuid>dcdb3b73-16f2-406b-9f94-32e270da12bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1 New Response' or . = '1 New Response')]</value>
      <webElementGuid>4f4758ae-3cc0-46ca-b706-4e56524287a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
