<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed</name>
   <tag></tag>
   <elementGuidId>088c21a3-1e69-490d-99d3-274d467bfffa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#policySubmitBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='policySubmitBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5c12172-8108-43e5-b0a6-97582c02758e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>policySubmitBtn</value>
      <webElementGuid>9e1e1ad5-e941-4075-a734-c740c8c75056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c151f4fc-c877-4404-b5d5-52bb259166b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next-button conditions-web skin-primary-main-bg</value>
      <webElementGuid>93f56620-fde1-4d12-8ce4-a6e29d4f2874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>onSubmitButtonClicked()</value>
      <webElementGuid>1e8cf136-0d32-410f-b587-f86e4848db0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed  </value>
      <webElementGuid>611dc080-a955-446c-be57-0121539dc616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policySubmitBtn&quot;)</value>
      <webElementGuid>bfd9f532-5133-4aa3-962d-4f3dc64c2906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='policySubmitBtn']</value>
      <webElementGuid>847f5275-f26f-4bec-b8d8-a5439caa408d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I Agree to the Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>07ded9c7-960d-4b9f-9dfb-184a0917807a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You agree that we reserve the right to monitor user access and the materials held within it.'])[1]/following::button[1]</value>
      <webElementGuid>52a3630f-f526-445a-bacf-a758464909f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fd69cc93-6252-4db6-ba11-77e102b2b74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'policySubmitBtn' and @type = 'submit' and (text() = 'Proceed  ' or . = 'Proceed  ')]</value>
      <webElementGuid>2beda6ba-f0b0-42d8-9411-de57dc7f4d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
