<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Send</name>
   <tag></tag>
   <elementGuidId>5f95153c-fabf-4850-a850-f0442a91d441</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.StyledBox-sc-13pk1d4-0.emZxKk.sendMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[2]/div/div/div[3]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d096e489-72ad-4f5e-9001-0062703a2e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5573238-7b47-4536-80ff-b6a2e3b136e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tut</name>
      <type>Main</type>
      <value>SendMessage</value>
      <webElementGuid>db8a99b3-c36d-42ec-821d-742a732790e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledBox-sc-13pk1d4-0 emZxKk sendMessage</value>
      <webElementGuid>fbe17d5b-df34-4492-adf8-8182a62eae4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>345f4c98-bb5d-4547-bab6-1fef4cec7ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;StyledGrommet-sc-19lkkz7-0 kRcOeE&quot;]/main[@class=&quot;StyledBox-sc-13pk1d4-0 duwRFe&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 vZMZQ&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cPthKx&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 hGKrqd&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cjzMPh&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 jSxRWn&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 gGmifu&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 dKiBuy&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 eMYBNT&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 emZxKk sendMessage&quot;]</value>
      <webElementGuid>7bc911f1-9063-41a3-aec8-0e6127d63c36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div/div[3]/div[2]/div/div/div</value>
      <webElementGuid>9595df7d-aa78-420b-a6d6-122d49686cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add People'])[2]/following::div[18]</value>
      <webElementGuid>268efca3-5f1a-4452-ae7c-42b00e21bc81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[1]</value>
      <webElementGuid>a80a2515-d6f3-4db9-9b61-a6ad911e1030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[2]/div/div/div</value>
      <webElementGuid>ffbe2247-ffec-4862-9ac7-aaf0a5140aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>443cea87-a33e-4794-bfcb-77de7785e569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
