<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leaderboard_obj1</name>
   <tag></tag>
   <elementGuidId>15025f90-d62b-4b3c-ac48-f12a21eb27da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td//span[contains(text(),'You')]//following::td[contains(@class,'StyledTable__StyledTableCell')]//span)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
