<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>leaderboard_obj2</name>
   <tag></tag>
   <elementGuidId>6ef9e225-76a0-4111-9579-31e172bdfb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//td//span[contains(text(),'You')]//following::td[contains(@class,'StyledTable__StyledTableCell')]//span)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
