<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send</name>
   <tag></tag>
   <elementGuidId>18513080-f26b-4421-84f5-8e4979b87736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-tut=&quot;SendMessage&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.StyledText-sc-1sadyjn-0.hNMsVQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3331ad31-4eea-401a-855d-bdc249ce54df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledText-sc-1sadyjn-0 hNMsVQ</value>
      <webElementGuid>89a99245-5d7e-4800-8254-4f14b5a431ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>69c6db9d-8684-4ba9-b8f4-2da528845c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;StyledGrommet-sc-19lkkz7-0 kRcOeE&quot;]/main[@class=&quot;StyledBox-sc-13pk1d4-0 duwRFe&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 vZMZQ&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cPthKx&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 hGKrqd&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cjzMPh&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 jSxRWn&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 gGmifu&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 dKiBuy&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 eMYBNT&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 emZxKk sendMessage&quot;]/span[@class=&quot;StyledText-sc-1sadyjn-0 hNMsVQ&quot;]</value>
      <webElementGuid>29dc0149-a18b-4975-9b21-a095a76131cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div/div[3]/div[2]/div/div/div/span</value>
      <webElementGuid>af71bb01-56eb-465d-a53d-9f9aa3349131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add People'])[2]/following::span[5]</value>
      <webElementGuid>97e8df79-1c12-471b-9877-94fa1c171304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>353642de-6141-4514-b3c7-b2e4dd0693f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>6f0bd41c-22da-424b-9547-e0362b04ccea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/span</value>
      <webElementGuid>5279e261-4468-4be2-8a4e-5ec3e50e98b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>5ebcecfd-ff2e-4a8b-ac87-f596b0f297e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
