<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start Simulation</name>
   <tag></tag>
   <elementGuidId>5d023831-21e5-4a77-b006-1ec7f4ad98ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.StyledText-sc-1sadyjn-0.dQJScS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/div[3]/div/div/div/div[4]/div/div/button/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3d0dc05e-fe59-4b7e-9b63-45423e6bcbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledText-sc-1sadyjn-0 dQJScS</value>
      <webElementGuid>c82227c6-73f7-4bf6-82f9-ad997156d59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Simulation</value>
      <webElementGuid>611dc88d-a7d9-4a34-aa40-385e64984b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;StyledGrommet-sc-19lkkz7-0 kRcOeE&quot;]/main[@class=&quot;StyledBox-sc-13pk1d4-0 duwRFe&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 dXKnTw&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 kLpmSB&quot;]/div[@class=&quot;StyledGrid-sc-1wofa1l-0 frcLTf&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 eAqFMh&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 bxTGIj&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 kxtEXP&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 fiNIBX&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 esYkNk&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 ekzXZz&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cKLqQe&quot;]/button[@class=&quot;StyledButton-sc-323bzc-0 eKoXRc&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 kIOiPS&quot;]/span[@class=&quot;StyledText-sc-1sadyjn-0 dQJScS&quot;]</value>
      <webElementGuid>aa0abf1d-3b15-4dbb-b1b4-1bfe147ecf8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/div[3]/div/div/div/div[4]/div/div/button/div/span</value>
      <webElementGuid>29299bbd-fbee-4366-a502-a1620ab76e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time limit:'])[1]/following::span[3]</value>
      <webElementGuid>34427c23-8d75-4f15-99a6-b3af170fd77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='at least 4 stars'])[2]/following::span[4]</value>
      <webElementGuid>3e573149-5cc3-43b2-a991-525317300d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Simulation']/parent::*</value>
      <webElementGuid>38d7c6f9-f0d8-49d1-b2ac-fae1b66c2b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/span</value>
      <webElementGuid>17f62f57-8f5e-436a-b3d0-62d7cea831d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Start Simulation' or . = 'Start Simulation')]</value>
      <webElementGuid>7909b0c9-b7d9-4def-a423-8ecbc2dca4b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
