<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add</name>
   <tag></tag>
   <elementGuidId>948a4227-6d82-4931-83a4-e08aef8d8cd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.StyledText-sc-1sadyjn-0.ILqvz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ZenConSol Inc.'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e09cb064-e32b-471e-bd42-7c8f22769f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledText-sc-1sadyjn-0 ILqvz</value>
      <webElementGuid>b972086d-3cad-4ecf-991c-ab39ce71c0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>745c43ab-4291-40a4-a3bf-5daed357742c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[3]/div[1]/div[@class=&quot;StyledLayer-sc-rmtehz-0 kCyckv&quot;]/div[@class=&quot;StyledLayer__StyledContainer-sc-rmtehz-2 gynaXQ&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 ihfbaW addOrgChart&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 fxPiOm&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 BshfS&quot;]/span[@class=&quot;StyledText-sc-1sadyjn-0 ILqvz&quot;]</value>
      <webElementGuid>95133a2c-ec96-4070-b39f-ba1038a96e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZenConSol Inc.'])[1]/following::span[1]</value>
      <webElementGuid>3161cc6e-bc17-4999-8c36-266e72f8c227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/following::span[2]</value>
      <webElementGuid>89e578da-3129-4e43-99a7-a4d72c6c5513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::span[1]</value>
      <webElementGuid>73057980-1bad-432d-be80-93b809017e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>371eaf85-fe5d-4d43-9e6d-1b91d30b550e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div[2]/div/span</value>
      <webElementGuid>6617e45e-75db-4dbc-b0c6-7a5fe3f7fb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>07cc4cb7-37ff-4ba6-af6a-49fdd33bd729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
