<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[contains(@style,'bottom')]</description>
   <name>newResponse_Button</name>
   <tag></tag>
   <elementGuidId>7559e25f-b10c-4f19-9cad-59844ca1d192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@style,'bottom')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
