<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Send</name>
   <tag></tag>
   <elementGuidId>7c5ab38f-988e-4309-96f7-92f815a05715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.StyledText-sc-1sadyjn-0.hNMsVQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-tut=&quot;SendMessage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>65f3d115-a9be-47e9-9ca1-8a4134817a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledText-sc-1sadyjn-0 hNMsVQ</value>
      <webElementGuid>88cf540e-b92b-4390-aa21-eacc3d6951ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>bb09c96e-4cf2-47a7-98a2-397884f36a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;StyledGrommet-sc-19lkkz7-0 kRcOeE&quot;]/main[@class=&quot;StyledBox-sc-13pk1d4-0 duwRFe&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 vZMZQ&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cPthKx&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 hGKrqd&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 cjzMPh&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 jSxRWn&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 gGmifu&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 dKiBuy&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 eMYBNT&quot;]/div[@class=&quot;StyledBox-sc-13pk1d4-0 emZxKk sendMessage&quot;]/span[@class=&quot;StyledText-sc-1sadyjn-0 hNMsVQ&quot;]</value>
      <webElementGuid>75204fe7-cac1-491b-9c78-9f342cee4434</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[2]/div/div/div[3]/div[2]/div/div/div/span</value>
      <webElementGuid>2c81a39f-3744-4a7d-8812-9941839dbdd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add People'])[2]/following::span[5]</value>
      <webElementGuid>aea345d8-68c8-41fe-b3b5-07353d7620ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[1]</value>
      <webElementGuid>ea5d45d6-12dc-4353-bed1-c4a9f2c5b3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send']/parent::*</value>
      <webElementGuid>50ee6208-94b4-4144-9083-9c670351138f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/span</value>
      <webElementGuid>0ac459b2-3d60-4bf7-ac9b-94e19ba05d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Send' or . = 'Send')]</value>
      <webElementGuid>452a29b5-3788-4e11-8f7a-299737b70c2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
