<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Intro_Next_Btn</name>
   <tag></tag>
   <elementGuidId>116c70be-d57f-4362-96d4-1e4c7ed53f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[contains(@style,'box-shadow')])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'next-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next-btn</value>
      <webElementGuid>3b5bf31a-b16e-4a18-be6e-c16c381cb28b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[name()='svg'][@id='next-btn']</value>
      <webElementGuid>684dea61-3036-4fc5-ae97-b7aae216b7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
